<template>
  <div class="page-container">
    <div class="content-wrapper">
      <h1>Privacy Policy</h1>
      <p class="last-updated">Last updated: July 24, 2024</p>
      
      <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
      
      <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>

      <h2>Interpretation and Definitions</h2>
      <h3>Interpretation</h3>
      <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
      <h3>Definitions</h3>
      <p>For the purposes of this Privacy Policy:</p>
      <ul>
        <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
        <li><strong>Application</strong> refers to BillBot ผู้ช่วย, the software program provided by the Company.</li>
        <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to BillBot ผู้ช่วย.</li>
        <li><strong>Country</strong> refers to: Thailand</li>
        <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
        <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
        <li><strong>Service</strong> refers to the Application.</li>
        <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
        <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
        <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
      </ul>

      <h2>Collecting and Using Your Personal Data</h2>
      <h3>Types of Data Collected</h3>
      <h4>Personal Data</h4>
      <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
      <ul>
        <li>Usage Data</li>
      </ul>
      
      <h4>Information from Receipts</h4>
      <p>When you submit receipts to the Service, we collect information from those receipts, which may include:</p>
      <ul>
        <li>Merchant name and address</li>
        <li>Date and time of purchase</li>
        <li>Items purchased and their prices</li>
        <li>Total amount and currency</li>
      </ul>
      <p>This information is used to provide the core functionality of the Service, which is to digitize and categorize your expenses.</p>

      <h3>Use of Your Personal Data</h3>
      <p>The Company may use Personal Data for the following purposes:</p>
      <ul>
        <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
        <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
        <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
        <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
      </ul>

      <h3>Data Deletion</h3>
      <p>You may request deletion of your data by following the instructions on our <router-link to="/user-data-deletion">Data Deletion page</router-link>.</p>

      <h2>Changes to this Privacy Policy</h2>
      <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
      <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>

      <h2>Contact Us</h2>
      <p>If you have any questions about this Privacy Policy, You can contact us:</p>
      <ul>
        <li>By email: <a href="mailto:support@billbotpoochuay.com">support@billbotpoochuay.com</a></li>
      </ul>
    </div>
  </div>
</template>

<style scoped>
.page-container {
  min-height: 100vh;
  background: var(--bg-secondary);
  padding: 140px 0 80px;
}

.content-wrapper {
  max-width: 800px;
  margin: 0 auto;
  padding: 0 24px;
  background: var(--bg-glass);
  border-radius: var(--border-radius-large);
  box-shadow: var(--shadow-light);
  backdrop-filter: blur(20px);
  -webkit-backdrop-filter: blur(20px);
  border: 1px solid rgba(255, 255, 255, 0.2);
  padding: 48px;
}

h1 {
  font-size: var(--font-size-5xl);
  font-weight: 700;
  color: var(--text-primary);
  margin-bottom: 16px;
  letter-spacing: -0.02em;
}

.last-updated {
  font-size: var(--font-size-sm);
  color: var(--text-secondary);
  margin-bottom: 32px;
  font-weight: 500;
}

h2 {
  font-size: var(--font-size-3xl);
  font-weight: 600;
  color: var(--text-primary);
  margin: 48px 0 24px 0;
  letter-spacing: -0.01em;
}

h3 {
  font-size: var(--font-size-2xl);
  font-weight: 600;
  color: var(--text-primary);
  margin: 32px 0 16px 0;
  letter-spacing: -0.01em;
}

h4 {
  font-size: var(--font-size-xl);
  font-weight: 600;
  color: var(--text-primary);
  margin: 24px 0 12px 0;
  letter-spacing: -0.01em;
}

p {
  font-size: var(--font-size-base);
  line-height: 1.6;
  color: var(--text-secondary);
  margin-bottom: 16px;
  font-weight: 400;
}

ul {
  padding-left: 24px;
  margin-bottom: 24px;
}

li {
  font-size: var(--font-size-base);
  line-height: 1.6;
  color: var(--text-secondary);
  margin-bottom: 8px;
  font-weight: 400;
}

a {
  color: var(--primary-color);
  text-decoration: none;
  font-weight: 500;
  transition: color 0.2s ease;
}

a:hover {
  color: var(--primary-dark);
}

strong {
  font-weight: 600;
  color: var(--text-primary);
}

/* Responsive Design */
@media (max-width: 768px) {
  .page-container {
    padding: 120px 0 60px;
  }
  
  .content-wrapper {
    padding: 32px 20px;
    margin: 0 16px;
  }
  
  h1 {
    font-size: var(--font-size-4xl);
  }
  
  h2 {
    font-size: var(--font-size-2xl);
    margin: 32px 0 16px 0;
  }
  
  h3 {
    font-size: var(--font-size-xl);
    margin: 24px 0 12px 0;
  }
}

@media (max-width: 480px) {
  .content-wrapper {
    padding: 24px 16px;
    margin: 0 12px;
  }
  
  h1 {
    font-size: var(--font-size-3xl);
  }
  
  h2 {
    font-size: var(--font-size-xl);
  }
  
  h3 {
    font-size: var(--font-size-lg);
  }
}
</style> 